language: php
php:
    - 7.0
install:
    - composer install
script:
    - mkdir -p build/logs
    - chmod 777 build/logs
    - cp phpunit.xml.dist phpunit.xml
    - php vendor/bin/phpunit --bootstrap app/bootstrap.php.cache --coverage-clover build/logs/clover.xml -c app/phpunit.xml src/
after_script:
    - php vendor/bin/coveralls -v